# Generated by Django 4.1 on 2022-09-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('post', '0003_tag_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Image1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Image2',
            new_name='image2',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.profile'),
        ),
    ]
